# -------------------------------ORGANIZE-CATEGORICALS-------------------------------

### Import Library's

In [18]:
import pandas as pd
import regex as re
import warnings
pd.options.display.max_rows = 10

warnings.filterwarnings("ignore")
warnings.warn("this will not show")

### Function

In [2]:
def organize_categoricals(data, target_col, prem_list, stan_list):
    '''
    This function is created to edit the excess unique values found in the data.
    '''
    
    
    for i in range(len(data)):
        premium, standart = 0, 0

        for prem in prem_list: 
            try:
                if prem == re.search(prem, data[target_col][i])[0]:
                    premium +=1
            except:
                pass
        for stan in stan_list: 
            try:
                if stan == re.search(stan, data[target_col][i])[0]:
                    standart +=1
            except:
                pass

        if premium == 0 and standart == 0:
            data[target_col][i] = data[target_col][i]
        else:
            try:
                if (100*premium)/(premium+standart) >= 50:
                    data[target_col][i] = 'Premium'
                else:
                    data[target_col][i] = 'Standart'
            except:
                data[target_col][i] = 'Standart'

##### The function groups premium and standard with simple mathematical operations.

Definition of the values we need to give to the function:
- data: your pandas dataframe you are working on
- target_col: column you want to edit
- prem_list = the first list created when you split the data in the column into two
    - Example: premium = ['Hilton Bathroom', 'Jacuzzi', 'Marble Floor', 'Furnished', 'Sauna', 'Terrace']
- stan_list = the second list created when you split the data in the column into two
    - Example: standart = ['ADSL', 'Wood Joinery', 'Built-in Kitchen', 'Balcony', 'Laundry Room']
    
            - Note: Make sure you get all the unique values in the column, otherwise you may not get good results.

### Example

In [16]:
df = pd.read_csv('example.csv')

In [20]:
df.head()

,type,room_type,area_m2,price,external_features,interior_features,location_features
0,Çiftlik Evi,5 + 2,580.0,2750000.0,"['Bahçeli', ' Otopark - Açık', ' PVC Doğrama',...","['Ahşap Doğrama', ' Ankastre Mutfak', ' Balkon...","['Caddeye yakın', ' Manzara - Doğa', ' Otobana..."
1,Daire,3 + 1,120.0,1275000.0,"['Asansör', ' Isı Yalıtım', ' Oyun Parkı', ' S...","['ADSL', ' Ahşap Doğrama', ' Alarm', ' Ankastr...","['Cadde Üzerinde', ' Caddeye yakın', ' Ön cephe']"
2,Daire,3 + 1,130.0,1375000.0,"['Asansör', ' Kapıcı']","['Balkon', ' Çelik Kapı', ' Duşakabin', ' Duva...","['Cadde Üzerinde', ' Manzara - Doğa']"
3,Villa,4 + 1,350.0,2950000.0,"['Bahçeli', ' Güvenlik', ' Isı Yalıtım', ' Oto...","['Balkon', ' Barbekü', ' Çamaşır Odası', ' Çel...","['Havaalanına yakın', ' Manzara', ' Manzara - ..."
4,Daire,3 + 1,145.0,2350000.0,"['Hidrofor', ' Kapıcı']","['Ahşap Doğrama', ' Alarm', ' Ankastre Mutfak'...","['Cadde Üzerinde', ' Havaalanına yakın', ' Man..."

- When we examine the data, we can say that the columns we want to organize are 'external_features', 'interior_features' and 'location_features'.

In [22]:
external_premium = ['Bahçeli', 'Fitness', 'Güvenlik', 'Hidrofor', 'Otopark - Kapalı', 'Siding', 'Site içerisinde', 'Tenis Kortu', 'Yüzme Havuzu', 'Ahşap Doğrama']
external_standart = ['Asansör', 'Cam Mozaik Kaplama', 'Isı Yalıtım', 'Jeneratör', 'Kapıcı', 'Otopark - Açık', 'Oyun Parkı', 'PVC Doğrama', 'Su deposu', 'Yangın Merdiveni']

interior_premium = ['Ebeveyn Banyolu', 'Giyinme Odası', 'Gömme Dolap', 'Hilton Banyo', 'Jakuzi', 'Mermer Zemin', 'Mobilyalı', 'Sauna', 'Teras', 'Vestiyer', 'Yerden Isıtma', 'Şömine', 'Görüntülü Diafon', 'Parke - Laminant', 'Klima', 'Seramik Zemin', 'Barbekü']
interior_standart = ['ADSL', 'Ahşap Doğrama', 'Ankastre Mutfak', 'Balkon', 'Çamaşır Odası', 'Çelik Kapı', 'Duşakabin', 'Duvar Kağıdı', 'Hazır Mutfak', 'Isıcam', 'Mutfak Doğalgazı', 'Panel Kapı', 'Panjur', 'Parke', 'Tavan Arası', 'Teras Kapalı', 'Alarm', 'Beyaz Eşyalı', 'Halı Kaplama', 'Kablo TV-Uydu', 'Kapalı Balkon', 'Kartonpiyer', 'Laminant Mutfak', 'Marley', 'Saten Alçı', 'Saten Boya', 'Spot Işık']

location_premium = ["Denize sıfır", "Denize yakın", "Havaalanına yakın", "Manzara - Boğaz", "Manzara - Deniz", "Manzara - Göl", "Ön cephe", "Metrobüse yakın", "Deniz Ulaşımına yakın", "Cadde Üzerinde", "Metroya yakın"]
location_standart = ["Arka cephe", "Caddeye yakın", "Manzara", "Manzara - Doğa", "Manzara - Şehir", "Merkezde", "Otobana yakın", "Toplu Ulaşıma yakın", "Tramvaya yakın", "Marmaraya yakın", "E-5'e yakın", "TEM'e yakın", "Minibüs / Dolmuşa yakın", "Avrasya Tüneli'ne yakın", "Boğaz köprülerine yakın"]

- While grouping at this step, your results will be better if you organize them as a result of researches related to that field.

In [23]:
organize_categoricals(df, 'external_features', external_premium, external_standart)

In [24]:
df.head()

,type,room_type,area_m2,price,external_features,interior_features,location_features
0,Çiftlik Evi,5 + 2,580.0,2750000.0,Standart,"['Ahşap Doğrama', ' Ankastre Mutfak', ' Balkon...","['Caddeye yakın', ' Manzara - Doğa', ' Otobana..."
1,Daire,3 + 1,120.0,1275000.0,Standart,"['ADSL', ' Ahşap Doğrama', ' Alarm', ' Ankastr...","['Cadde Üzerinde', ' Caddeye yakın', ' Ön cephe']"
2,Daire,3 + 1,130.0,1375000.0,Standart,"['Balkon', ' Çelik Kapı', ' Duşakabin', ' Duva...","['Cadde Üzerinde', ' Manzara - Doğa']"
3,Villa,4 + 1,350.0,2950000.0,Standart,"['Balkon', ' Barbekü', ' Çamaşır Odası', ' Çel...","['Havaalanına yakın', ' Manzara', ' Manzara - ..."
4,Daire,3 + 1,145.0,2350000.0,Premium,"['Ahşap Doğrama', ' Alarm', ' Ankastre Mutfak'...","['Cadde Üzerinde', ' Havaalanına yakın', ' Man..."

###### As can be seen, groupings were made according to the operation performed in the function. It's just a simple operation, with other ideas the function can be improved and the calculation modified. Now we can examine this situation in other columns.

In [25]:
organize_categoricals(df, 'interior_features', interior_premium, interior_standart)
organize_categoricals(df, 'location_features', location_premium, location_standart)

In [26]:
df.head(10)

,type,room_type,area_m2,price,external_features,interior_features,location_features
0,Çiftlik Evi,5 + 2,580.0,2750000.0,Standart,Standart,Standart
1,Daire,3 + 1,120.0,1275000.0,Standart,Standart,Premium
2,Daire,3 + 1,130.0,1375000.0,Standart,Standart,Standart
3,Villa,4 + 1,350.0,2950000.0,Standart,Premium,Standart
4,Daire,3 + 1,145.0,2350000.0,Premium,Standart,Standart
5,Villa,5 + 1,350.0,11750000.0,Standart,Standart,Standart
6,Daire,3 + 1,130.0,1250000.0,Standart,Standart,Premium
7,Daire,3 + 1,120.0,1150000.0,Standart,Standart,Premium
8,Daire,1 + 1,38.0,1250000.0,Premium,Standart,Standart
9,Villa,4 + 1,350.0,2950000.0,Standart,Standart,Standart